FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN yarn cache clean

RUN npm install

COPY ./src/.env.prod ./src/.env

COPY . .

EXPOSE 8888

RUN npm run build

CMD ["npm", "run", "start"]

