on:
  push:
    branches: [ build/release ]

name: Deploy "E-COMMERCE PHARMACY ALTEACARE" to Production Environment

jobs:
  deploy:
    name: Deploy "E-COMMERCE PHARMACY ALTEACARE" to Production Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NODE_ENV: production
          envkey_PORT: 8888
          envkey_NEXT_PUBLIC_BASE_URL_ENTRYPOINT: https://services.alteacare.com/
          envkey_NEXT_PUBLIC_BASE_URL_MIDTRANS: https://app.midtrans.com/snap/snap.js
          envkey_NEXT_PUBLIC_CLIENT_KEY: Mid-client-4I5ghLJtXNmU6ZHA
          directory: ./src

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --confirm'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          alias-domains: pharmacy.alteacare.com
          working-directory: ./
          scope: ${{ secrets.TEAM_ID }}
          github-comment: false

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'deployment-information'
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: 'AlteaCare Bot'
          SLACK_ICON: 'https://alteacare-assets.s3.ap-southeast-1.amazonaws.com/images/logo_48x48.png'
          SLACK_FOOTER: 'AlteaCare Deployment Information'